### ISSUE TITLE
plot examples in vignette

### ISSUE THREAD

**Issue by srcorsi-USGS** [USGS-R/toxEval#237]
When I copy/paste the graphics examples for boxplots and stacked bars, the code for the examples currently just plots the next graph right on top of the previous graph rather than making a new plot page in RStudio. How do we tell ggplot to put it in the next page without clearing out all plots with dev.off()?

#Single site example
library(dplyr)

maumee <- filter(chemicalSummary, shortName == "Maumee")
maumee_site <- filter(tox_list$chem_site, `Short Name` == "Maumee")

maumee_plot <- plot_tox_boxplots(maumee, "Biological",title = maumee_site$Fullname[1])

gb <- ggplot2::ggplot_build(maumee_plot)
gt <- ggplot2::ggplot_gtable(gb)
gt$layout$clip[gt$layout$name=="panel"] <- "off"
grid::grid.draw(gt)

stack_plot <- plot_tox_stacks(chemicalSummary, 
                              chem_site = tox_list$chem_site, 
                              category =  "Biological")

gb <- ggplot2::ggplot_build(stack_plot)
gt <- ggplot2::ggplot_gtable(gb)
gt$layout$clip[gt$layout$name=="panel-1-1"] = "off"
grid::grid.draw(gt)

![image](https://user-images.githubusercontent.com/1444781/39317190-9a5429ce-4940-11e8-9c2a-be506511fdd1.png)

@ldecicco-USGS

**Comment by srcorsi-USGS** [comment]
@ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
Because of that clipping business, it just keeps plotting over the last one. There's not a super great solution here. We could not advertise the clipping code in the app. The we'd need to rely on the user reading about the clipping code in the vignette. That's why I added the section in the vignette:  "What is the "clipping" code???" (in basicWorkflow). 

I'd recommend just looking at the graphs in RStudio as they come out of the `toxEval` functions. I only use the clipping features when I'm saving the plot.

**Comment by ldecicco-USGS** [comment]
Oh, but if you do want to look at the unclipped graph in RStudio, then you need to run `dev.off()` when you are done, or clear the plots with the broom icon in the Plot tab.

**Comment by srcorsi-USGS** [comment]
OK, so to keep the graph in the RStudio plots memory, you can just create an empty plot like this:
plot(x=1,type="n",bty="n",xaxt="n",yaxt="n",xlab="",ylab="")
That clears it out and the next toxEval graph looks clean.
Not sure if we want to include that in the documentation as an aside for people running multiple graphs.

**Comment by ldecicco-USGS** [comment]
My vote would be to remove all the clipping code on the app. The app users are the most afraid of R (otherwise they'd just be using the functions). Therefore, we don't want to confuse them with this. And as I mention in the vignette, there is probably going to be an update to `ggplot2` soon enough that will not require all these extra steps. 

So...if we take it out of the app output, then I think we don't need to confuse people too much with these directions. Most of the time, people won't need to preview the unclipped version in RStudio *and* retain that plot (what you are describing). So, the only time to add this discussion is in the  "What is the "clipping" code???" section (and maybe "How to save a plot?")

I think instead of that whole empty plot function, a little easier is:
```r
plot.new()
```

**Comment by srcorsi-USGS** [comment]
Actually, I think that many R users will make their coding easier by get code examples from the app and modifying from there (that is what I have been doing). Maybe it isn't critical to have the clipping code there, but if not, we should add a section into the shinyApp vignette mentioning that they could use these 4 lines of code to improve output. Then again, if people are copying code from the app and running scripts, there will be a subset of those people that don't read the vignette, and will just send emails asking how to fix it when they see text getting sliced off. More questions to answer for the toxEval help group. So, which will cause more questions--including it or excluding it in the app?

**Comment by ldecicco-USGS** [comment]
I vote is that including it (in the app) will cause more questions. The questions we'd get would be "Why do the top line get clipped?", and we can have an easy answer, in the vignette, in the help files, and on the readme all available.

**Comment by srcorsi-USGS** [comment]
OK, feel free to remove it from the app, but let's put something in the app vignette to explain how to reconcile that.
