### ISSUE TITLE
function clean_endPoint_info

### ISSUE THREAD

**Issue by srcorsi-USGS** [USGS-R/toxEval#246]
I am wondering if this needs to be a function that the user needs access to. Is it optional to run it? If not, maybe it should be behind the scenes.

**Comment by ldecicco-USGS** [comment]
Since it's altering the original ToxCast endpoints...I kind of like having the user acknowledge that they are doing it.

Also, keeping it exported means localizing the description of what's happening to just that help file. Otherwise, you might need to put an asterisk after each mention of ToxCast to describe that it's modified by all this stuff from Dan's paper.
